name: Run tests on CI

on: 
  push:
    branches:
      - master

env:
  LOGIN_USER: ${{ secrets.LOGIN_USER }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  run_api_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --force

    - name: Install playwright
      run: npx playwright install
    
    - name: Run api test createDeleteArticle
      run: npx playwright test "createDeleteArticle.spec.spec.ts" --project=regression

    - name: Run test likesCounter
      run: npx playwright test likesCounter.spec.ts --project=likesCounter

    - name: Run test likesCounterGlobal
      run: npx playwright test --project=likesCounterGlobal

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30