name: Api tests run on CI

on: 
  push:
    branches:
      - master

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --force

    - name: Install playwright
      run: npx playwright install
    
    - name: Run tests
      run: npx playwright test "workingWithAPI.spec.ts" -g "Create\s+and\s+delete\s+article\s+via\s+API$"

    - name: Print hello world
      run: echo 'Hello World1'