name: Api test run on CI

on: 
  push:
    branches:
      - master

jobs:
  run_api_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --force

    - name: Install playwright
      run: npx playwright install
    
    - name: Run tests
      run: npx playwright test "workingWithAPI.spec.ts" -g "Create\s+and\s+delete\s+article\s+via\s+API$"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30