name: Api_tests
on: 
  push:
    branches:
      - master

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello world
      run: echo 'Hello World1'

  build2:
    runs-on: ubuntu-latest
    needs: [build1]
    steps:
    - name: Print hello world
      run: echo 'Hello World2'
